<template>
  <svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg">
    <circle
      cx="50"
      cy="50"
      r="40"
      stroke="currentColor"
      stroke-width="2"
      fill="none"
      opacity="0.3"
    />
    <circle
      cx="50"
      cy="50"
      r="25"
      stroke="currentColor"
      stroke-width="1"
      fill="none"
      opacity="0.5"
    />
  </svg>
</template>
